# ===============================
# CONFIGURAÇÕES DO BANCO DE DADOS (POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_db
spring.datasource.username=seu_usuario_postgres
spring.datasource.password=sua_senha_postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Imprime as queries SQL no terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Comportamento de criação das tabelas
spring.jpa.hibernate.ddl-auto=update

# Dialeto do PostgreSQL para que o Hibernate saiba traduzir o Java para o SQL correto
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# EXECUÇÃO DO SCRIPT SQL INICIAL
# ===============================
spring.sql.init.mode=always